import "./globals.css";
import "./components/shell/shell.css";
import "./components/shell/alarm.css";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <footer className="copyright">
          Copyrightⓒ 2026 UND Co., Ltd. All rights reserved
        </footer>
      </body>
    </html>
  );
}
